server:
  port: 8788

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangdengke2000/config-2004.git
          search-paths: /
          username:
          password:
          skip-ssl-validation: true
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
