server:
  port: 8777

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/king-unmatched/config-service.git
          search-paths: /
          username:
          password:
          skip-ssl-validation: true
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka