server:
  port: 8888

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka

zuul:
  routes:
    web:
      path: /web/**
      serviceId: web
    order:
      path: /feigin/**
      serviceId: feigin
