server:
  port: 8780

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 20MB
  application:
    name: web
  main:
    allow-bean-definition-overriding: true
file:
  filepath: D:/QMDownload/Hotfix2/
